version: '3.2'

services:
   db:
      image: mysql:5.7
      container_name: Database
      restart: always
      ports:
       - '3306:3306'
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_DATABASE: db
        MYSQL_USER: user
        MYSQL_PASSWORD: root

   app:
      depends_on:
       - db
      image: phpmyadmin/phpmyadmin
      container_name: databrowser
      restart: always
      ports:
       - '8080:80'
      environment:
        PMA_HOST: db